-

  # Target: where our play will run and options it will run with
  hosts: localhost
  connection: local
  vars:
    do_token: "{{ hostvars['localhost']['dropletoken'] }}"

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
  - ping:
  - debug: msg="IP is {{ do_token }}"  
